language: python

sudo: true

services:
  - mysql

python:
  - "2.7"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests

before_script:



script:
  - pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD tests/newTest.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD --suitestatlevel 2 tests


env:
  matrix:
  - BROWSER=chrome
