language:
 - node_js
 - python


sudo: true
dist: trusty

services:
  - mysql

python:
  - "2.7"

node_js:
  - "0.8"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests

before_install:

### Pokus 1 ###
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo apt-get install libxss1 libappindicator1 libindicator7
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - sudo apt-get install -f

### Pokus 2 ###
  #- sudo apt-get install chromium-chromedriver
  - cd /
  - ls -la
  - cd home/travis
  - ls -la
  - cd local/
  - ls -la

### Pokus 3 ###
  #- export CHROME_BIN=/usr/bin/google-chrome
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- sudo apt-get update
  #- sudo apt-get install libxss1 libappindicator1 libindicator7
  #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  #- sudo dpkg -i google-chrome*.deb
  #- sudo apt-get install -f

  - sudo apt-get install xvfb

  - sudo apt-get install unzip

  - wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver

  - pwd
  - ls -la

  #- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  #- sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver


before_script:
  - cd home/travis/build/kubik335/zkouska

script: pybot tests/newTest.robot

