language: python
          node_js

sudo: true
dist: trusty

services:
  - mysql

python:
  - "2.7"

node_js:
    - "0.8"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests


before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

before_script:

  #- sudo apt-get install chromium-browser
  #- sudo apt-get install libnspr4-0d
  #- sudo apt-get install libcurl3
  #- wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  #- sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  #- sudo apt-get update
  #- sudo dpkg -i google-chrome-stable_current_amd64.deb
  #- sudo apt-get install google-chrome-stable
  #- sudo dpkg -i google-chrome-stable



  ### Google chrome ###

  #- sudo apt-get install libxss1 libappindicator1 libindicator7
  #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  #- pwd
  #- ls -a
  #- sudo dpkg -i google-chrome-stable_current_amd64.deb﻿
  #- sudo apt-get install -f
  #- sudo apt-get instal google-chrome-stable_current_amd64.deb﻿


  #- sudo apt-get install xvfb

  #- sudo apt-get install unzip

  #- wget -N http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  #- unzip chromedriver_linux64.zip
  #- chmod +x chromedriver

  #- sudo mv -f chromedriver /usr/local/share/chromedriver
  #- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  #- sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

  ### Chromedriver ###

  #- wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  #- pwd
  #- unzip chromedriver_linux64.zip
  #- export CHROME_BIN=chromium-browser
  #- "export DISPLAY=:99.0"
  #- "sh -e /etc/init.d/xvfb start"
  #- pwd
  #- ls -a

  ### Add chromediver to Path ###
  - echo $PATH
  - PATH=$PATH:/home/travis/build/kubik335/zkouska/chromedriver.exe
  - echo $PATH

script:
  - pybot tests/newTest.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD --suitestatlevel 2 tests


