language: python

sudo: true

services:
  - mysql

python:
  - "2.7"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests


before_script:
  #- sudo apt-get install chromium-browser
  - sudo apt-get install libnspr4-0d
  - sudo apt-get install libcurl3
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  #- sudo apt-get install google-chrome-stable
  #- sudo dpkg -i google-chrome-stable

script:
  - pybot tests/newTest.robot
  #- pybot -v BROWSER:$BROWSER -v "VALID USER":$TL_USER -v "VALID PASSWD":$TL_PASSWD --suitestatlevel 2 tests


