language:
 - node_js
 - python


sudo: true
dist: trusty

services:
  - mysql

python:
  - "2.7"

node_js:
  - "0.8"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - ls -a
  - sudo apt-get install chromium-chromedriver
  - ls -a

before_script:


script: pybot tests/newTest.robot

