language:
 - python


sudo: true
dist: trusty

services:
  - mysql

python:
  - "2.7"


install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests

before_install:

### Pokus 1 ###
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - sudo apt-get install libxss1 libappindicator1 libindicator7
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome-stable_current_amd64.deb
  - sudo apt-get install -f

### Pokus 2 ###
  #- sudo apt-get install chromium-chromedriver

  - cd $HOME
  #- ls -la
  #- cd .local/
  #- ls -la
  #- cd home/travis
  #- cd .bash_profile/
  #- ls -la
  #- ls -la
  #- cd home/travis
  #- cd .bash_profile/
  #- ls -la

### Pokus 3 ###
  #- export CHROME_BIN=/usr/bin/google-chrome
  #- export DISPLAY=:99.0
  #- sh -e /etc/init.d/xvfb start
  #- sudo apt-get update
  #- sudo apt-get install libxss1 libappindicator1 libindicator7
  #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  #- sudo dpkg -i google-chrome*.deb
  #- sudo apt-get install -f

  - sudo apt-get install xvfb

  - sudo apt-get install unzip

  - wget -N http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver

  #- sudo mv -f chromedriver .local/share/chromedriver
  #- ls -la
  #- sudo ln -s .local/share/chromedriver .local/bin/chromedriver
  #- ls -la
  #- sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver

  - mkdir -p $HOME/bin
  - mv chromedriver $HOME/bin
  - echo "export PATH=$PATH:$HOME/bin" >> $HOME/.bash_profile

before_script:
  - cd $HOME
  - cd build/kubik335/zkouska

script: pybot -v BROWSER:$BROWSER tests/newTest.robot

env:
  matrix:
  - BROWSER=chrome

