language:
 - node_js
 - python


sudo: true
dist: trusty

services:
  - mysql

python:
  - "2.7"

node_js:
  - "0.8"

install:
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install decorator
  - pip install docutils
  - pip install -U requests
  - pip install -U robotframework-requests

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - npm ./install js
  - npm install chromedriver
  - npm install chromedriver --chromedriver_cdnurl=http://npm.taobao.org/mirrors/chromedriver

script: ./node_modules/.bin/karma start --single-run --browsers Firefox

